pring:
  profile: test

#    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;

spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.show_sql: true
logging.level.me.aliprax: DEBUG

spring:
  datasource:
    username: postgres
    password: P@ssw0rd
    url: jdbc:postgresql://localhost:5432/h3

server:
  port: 8085